/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.plugin.neo4j;

import io.airlift.log.Logger;
import io.airlift.slice.Slice;
import io.trino.spi.Page;
import io.trino.spi.block.Block;
import io.trino.spi.connector.ConnectorPageSink;
import io.trino.spi.type.Type;
import org.neo4j.driver.Session;
import org.neo4j.driver.SessionConfig;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

import static io.trino.spi.type.BigintType.BIGINT;
import static io.trino.spi.type.BooleanType.BOOLEAN;
import static io.trino.spi.type.DoubleType.DOUBLE;
import static java.util.Objects.requireNonNull;
import static java.util.concurrent.CompletableFuture.completedFuture;

public class Neo4jPageSink
        implements ConnectorPageSink
{
    private static final Logger log = Logger.get(Neo4jPageSink.class);

    private final Neo4jSession neo4jSession;
    private final String tableName;
    private final List<Neo4jColumnHandle> columns;
    private long rowsWritten;

    public Neo4jPageSink(
            Neo4jSession neo4jSession,
            String tableName,
            List<Neo4jColumnHandle> columns)
    {
        this.neo4jSession = requireNonNull(neo4jSession, "neo4jSession is null");
        this.tableName = requireNonNull(tableName, "tableName is null");
        this.columns = requireNonNull(columns, "columns is null");
        this.rowsWritten = 0;
    }

    @Override
    public CompletableFuture<?> appendPage(Page page)
    {
        for (int position = 0; position < page.getPositionCount(); position++) {
            Map<String, Object> properties = new HashMap<>();

            for (int channel = 0; channel < page.getChannelCount(); channel++) {
                Block block = page.getBlock(channel);
                Neo4jColumnHandle column = columns.get(channel);

                // Skip the 'id' column as it's auto-generated by Neo4j
                if (column.getName().equals("id")) {
                    continue;
                }

                if (!block.isNull(position)) {
                    Object value = getValueFromBlock(block, position, column.getType());
                    properties.put(column.getName(), value);
                }
            }

            writeNode(tableName, properties);
            rowsWritten++;
        }

        return NOT_BLOCKED;
    }

    private Object getValueFromBlock(Block block, int position, Type type)
    {
        if (type.equals(BIGINT)) {
            return type.getLong(block, position);
        }
        else if (type.equals(DOUBLE)) {
            return type.getDouble(block, position);
        }
        else if (type.equals(BOOLEAN)) {
            return type.getBoolean(block, position);
        }
        else {
            // Treat as VARCHAR
            Slice slice = type.getSlice(block, position);
            return slice.toStringUtf8();
        }
    }

    private void writeNode(String label, Map<String, Object> properties)
    {
        try (Session session = neo4jSession.getDriver().session(SessionConfig.forDatabase(neo4jSession.getDatabase()))) {
            // Build CREATE query with parameters
            String query = String.format("CREATE (n:%s $props)", label);

            log.debug("Executing CREATE: %s with properties: %s", query, properties);
            session.run(query, Map.of("props", properties));
        }
        catch (Exception e) {
            log.error(e, "Failed to write node to Neo4j: label=%s, properties=%s", label, properties);
            throw new RuntimeException("Failed to write data to Neo4j", e);
        }
    }

    @Override
    public CompletableFuture<Collection<Slice>> finish()
    {
        log.info("Finished writing %d rows to Neo4j table %s", rowsWritten, tableName);
        return completedFuture(List.of());
    }

    @Override
    public void abort()
    {
        log.warn("Aborting write operation for table %s after writing %d rows", tableName, rowsWritten);
    }
}
